### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [5]:
arr_1 = np.arange(0, 9)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

2. Create a 3x3 numpy of all True 

In [68]:
arr_2 = np.ones((3,3), dtype = bool)
arr_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [3]:
arr_3 = np.arange (20, 40)
arr_3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [6]:
arr_3[arr_3%2 !=0] =-1
arr_3

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [8]:
arr_4 = np.arange(1, 20, 2)
arr_5 = np.arange(1, 20, 4)
arr_5

array([ 1,  5,  9, 13, 17])

In [12]:
common = np.intersect1d(arr_4, arr_5)
common


array([ 1,  5,  9, 13, 17])

6.  Create a 5x5 identity matrix

In [13]:
lst = np.arange(1, 26)
arr_6 = np.matrix(lst)
arr_6.reshape(5,5)

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [20]:
x = np.array([10, 12, 8, 2, 20])
y= np.linspace(10, 20, 101)
z= np.ones((2,3))


In [16]:
x

array([10, 12,  8,  2, 20])

In [21]:
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [18]:
z

array([[1., 1., 1.],
       [1., 1., 1.]])

8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [22]:
#mean
avg_x = np.mean(x)
avg_x

10.4

In [23]:
#standard deviation
std_x = np.std(x)
std_x

5.851495535331117

9. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
arr_7 = np.random.randint(1, 500, size=100)
arr_7

array([  4, 416, 331, 347, 125,  96, 302,  46, 488, 348, 212, 157, 347,
        22, 492, 398, 394, 148, 351, 360, 329,  85, 256,  45, 200, 168,
       408, 123, 114, 289, 227, 107, 436, 443, 285,  69, 427, 252,  85,
       138,  79, 467, 258, 307, 287, 355, 317, 389, 491, 307, 371, 100,
       129, 269, 499, 283, 132, 298, 217,  96, 396, 247, 251, 385, 125,
        25, 339, 262,  56,  39, 143, 283, 125, 127,  61, 132, 425, 252,
       416, 315, 459, 462,  12, 179, 354, 250, 494,  45, 429, 319, 347,
        10, 386, 479, 124, 353, 458, 455, 163, 168])

In [26]:
arr_7.reshape((10,10))

array([[  4, 416, 331, 347, 125,  96, 302,  46, 488, 348],
       [212, 157, 347,  22, 492, 398, 394, 148, 351, 360],
       [329,  85, 256,  45, 200, 168, 408, 123, 114, 289],
       [227, 107, 436, 443, 285,  69, 427, 252,  85, 138],
       [ 79, 467, 258, 307, 287, 355, 317, 389, 491, 307],
       [371, 100, 129, 269, 499, 283, 132, 298, 217,  96],
       [396, 247, 251, 385, 125,  25, 339, 262,  56,  39],
       [143, 283, 125, 127,  61, 132, 425, 252, 416, 315],
       [459, 462,  12, 179, 354, 250, 494,  45, 429, 319],
       [347,  10, 386, 479, 124, 353, 458, 455, 163, 168]])

In [27]:
np.max(arr_7)

499

In [28]:
np.min(arr_7)

4

10. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
arr_8 = np.matrix(np.arange(0, 9)).reshape(3,3)
arr_8

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [31]:
arr_9 = np.array([[1, 2, 3], [4, 5, 6]])
arr_9

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [32]:
arr_10 = np.array([0, 2.5, 5, 7.5, 10])
arr_10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [34]:
np.linspace(0.1, 10, 12)

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [35]:
np.full((5,7),10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

Numpy arrays run faster and have efficient memory more than lists.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [37]:
arr_11 = np.ones(50)
arr_11[1::2] = 0
arr_11

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [38]:
arr_12 = np.eye(10)
arr_12

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [39]:
arr_12 = np.eye(10)
arr_12

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [41]:
a= np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
np.dot(a,b)

matrix([[19, 22],
        [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [40]:
a= np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
a*b

matrix([[19, 22],
        [43, 50]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [45]:
c= np.matrix([[1,2],[3,4]])
d= 5
d*c

matrix([[ 5, 10],
        [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [51]:
A = np.array([[1,2],[3,4]])
A


array([[1, 2],
       [3, 4]])

In [52]:
B = A.transpose()
B

array([[1, 3],
       [2, 4]])

In [53]:
A*B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [54]:
D = np.array([[1,2],[3,4]])
D

array([[1, 2],
       [3, 4]])

In [55]:
E = np.array([[5,6],[7,8]])
E

array([[5, 6],
       [7, 8]])

In [56]:
D*E

array([[ 5, 12],
       [21, 32]])

In [57]:
E*D

array([[ 5, 12],
       [21, 32]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [61]:
arr_13 = np.matrix([[0, 1, 2], [3, 4, 5]])
arr_13



matrix([[0, 1, 2],
        [3, 4, 5]])

In [62]:
first_row = arr_13[0,:]
second_row = arr_13[1,:]
second_col = arr_13[:,1]
firstrow_third_col = arr_13[0,2]

In [63]:
first_row

matrix([[0, 1, 2]])

In [64]:
second_row

matrix([[3, 4, 5]])

In [65]:
second_col

matrix([[1],
        [4]])

In [66]:
firstrow_third_col

2